/**
 * Asset maps the PHP side reads, regenerated after every build:
 *
 *   asset-versions.php       plugin-relative asset path => 12-hex sha256 (applied as ?ver=
 *                            by Audit_Fixes::asset_url for the per-file delivery fallback)
 *   asset-min-map.php        empty since 9.3: minified twins are gone, the engine serves
 *                            built bundles and the fallback serves readable sources
 *   integrity-manifest.json  bytes + sha256 of every shipped file (Production::integrity_scan)
 *
 * Shipped = what tools/zip.mjs packages; the exclusion list is shared through EXCLUDED.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Development-only paths, relative to the plugin root (directories end with /). */
export const EXCLUDED = ['node_modules/', 'src/', 'tools/', '.build-check/', '.git/', 'package.json', 'package-lock.json', '.DS_Store'];

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

export function isShipped(rel) {
	return !EXCLUDED.some((rule) => (rule.endsWith('/') ? rel === rule.slice(0, -1) || rel.startsWith(rule) : rel === rule || rel.endsWith('/' + rule)));
}

export function shippedFiles(root) {
	const out = [];
	const walk = (dir) => {
		for (const entry of readdirSync(dir, { withFileTypes: true })) {
			const abs = join(dir, entry.name);
			const rel = relative(root, abs).split('\\').join('/');
			if (!isShipped(rel)) continue;
			if (entry.isDirectory()) walk(abs);
			else if (entry.isFile()) out.push(rel);
		}
	};
	walk(root);
	return out.sort();
}

export function writeAssetMaps(root, version) {
	const files = shippedFiles(root);
	/* Built bundles already carry a content hash in their file name, so they never get a ?ver. */
	const assets = files.filter((rel) => /^(assets|pro\/assets|modules)\//.test(rel) && /\.(css|js)$/.test(rel) && !rel.startsWith('assets/dist/'));
	let php = '<?php\n// Generated by tools/build.mjs: asset path => 12-hex sha256 of contents, applied as ?ver=.\nreturn array(\n';
	for (const rel of assets) php += ` '${rel}' => '${sha256(readFileSync(join(root, rel))).slice(0, 12)}',\n`;
	php += ');\n';
	writeFileSync(join(root, 'asset-versions.php'), php);
	writeFileSync(join(root, 'asset-min-map.php'), '<?php\n// Generated by tools/build.mjs. Since 9.3 no minified twins ship: the engine serves assets/dist bundles\n// and the per-file fallback serves the readable sources, so this map is empty by design.\nreturn array();\n');

	const manifest = { algorithm: 'sha256', built: new Date().toISOString().replace('Z', '+00:00'), version, bytes: 0, count: 0, files: {} };
	for (const rel of shippedFiles(root)) {
		if (rel === 'integrity-manifest.json') continue;
		const buf = readFileSync(join(root, rel));
		manifest.files[rel] = { bytes: buf.length, sha256: sha256(buf) };
		manifest.bytes += buf.length;
		manifest.count++;
	}
	writeFileSync(join(root, 'integrity-manifest.json'), JSON.stringify(manifest, null, 4) + '\n');
	return { assets: assets.length, files: manifest.count, bytes: manifest.bytes };
}

export function pluginVersion(root) {
	const main = readFileSync(join(root, 'delicat-builder-v9.php'), 'utf8');
	const m = /^\s*\*\s*Version:\s*(.+)$/mi.exec(main);
	return m ? m[1].trim() : '';
}
