<?php
/**
 * Rebuild the two concatenated CSS bundles.
 *
 * The storefront ships one request for the page chrome and one for the
 * component library. Both are plain concatenations, in cascade order, of files
 * that are already minified at source — editing a part has no effect on the
 * bundle until this runs, which is how the chrome bundle came to carry a stale
 * copy of the menu stylesheet.
 *
 * The generator used to live in scripts/refresh-delicat-assets.py, which is not
 * part of the distributed plugin, so the part lists are declared here instead.
 * Run this before tools/rebuild-assets.php: the hashes are taken from these
 * files' final contents.
 *
 *   php tools/rebuild-bundles.php           # report what would change
 *   php tools/rebuild-bundles.php --write   # apply
 *
 * @package Delicat_Builder_V9
 */

$root  = dirname( __DIR__ );
$write = in_array( '--write', $argv, true );

$bundles = array(
	'assets/css/storefront-chrome.min.css' => array(
		'assets/css/theme-system.css',
		'assets/dsb8-beta2-header.css',
		'assets/css/menu.css',
		'assets/css/bottom-nav.css',
	),
	'assets/components/all-components.min.css' => array(
		'assets/components/base.css',
		'assets/components/testimonials.css',
		'assets/components/trust-strip.css',
		'assets/components/products.css',
		'assets/components/newsletter.css',
		'assets/components/how-it-works.css',
		'assets/components/hero.css',
		'assets/components/bon-kliyan.css',
		'assets/components/text.css',
		'assets/components/banner.css',
		'assets/components/category-chips.css',
		'assets/components/faq.css',
		'assets/components/why-delicat.css',
		'assets/components/favorites.css',
		'assets/components/spacer.css',
	),
);

$changed = 0;

foreach ( $bundles as $target => $parts ) {
	$out = "/* Generated by tools/rebuild-bundles.php. Do not edit by hand.\n * Concatenation, in cascade order, of:\n";
	foreach ( $parts as $part ) {
		$out .= ' *   ' . $part . "\n";
	}
	$out .= " */\n\n";

	foreach ( $parts as $part ) {
		$path = $root . '/' . $part;
		if ( ! is_file( $path ) ) {
			fwrite( STDERR, "missing part: $part\n" );
			exit( 1 );
		}
		$out .= '/* --- ' . $part . " --- */\n" . trim( (string) file_get_contents( $path ) ) . "\n\n";
	}

	$existing = is_file( $root . '/' . $target ) ? (string) file_get_contents( $root . '/' . $target ) : '';
	$same     = $existing === $out;
	printf( "%-44s %s (%d bytes, %d parts)\n", $target, $same ? 'unchanged' : 'REBUILD', strlen( $out ), count( $parts ) );

	if ( $same ) {
		continue;
	}
	++$changed;
	if ( $write ) {
		file_put_contents( $root . '/' . $target, $out );
	}
}

if ( ! $write && $changed > 0 ) {
	echo "\nnothing written. re-run with --write to apply.\n";
} elseif ( $write ) {
	printf( "\nwritten. %d bundle(s) rebuilt.\n", $changed );
}
