#!/usr/bin/env python3
"""Rebuild the content-addressed asset layer of delicat-builder-v9.

Run after editing any CSS/JS in the plugin:

    python3 scripts/refresh-delicat-assets.py [delicat-builder-v9]

It (1) writes one `<name>.<12-hex-sha256>.<ext>` copy per source stylesheet/script
under assets/, pro/assets/ and modules/**/assets/ (superseded copies are KEPT so
already-cached HTML still resolves; pass --prune to remove them),
(2) regenerates asset-versions.php, and (3) regenerates integrity-manifest.json
with the plugin version read from the main plugin header.
"""
import datetime
import hashlib
import json
import os
import re
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else "delicat-builder-v9"
HASHED = re.compile(r"^(.*)\.([0-9a-f]{12})\.(css|js)$")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def asset_dir(relpath):
    return relpath.startswith("assets/") or relpath.startswith("pro/assets/") or (
        relpath.startswith("modules/") and "/assets/" in relpath
    )


# 0. storefront chrome bundle --------------------------------------------------
# Delicat_Builder_V9_Assets::enqueue_theme_assets() DEQUEUES the four chrome stylesheets
# and serves this one bundle instead. It shipped as a hand-built artifact that nothing in
# the repository could rebuild, so it went stale: every edit to its sources since it was
# built has been dead on arrival, including the drawer's whole open-state reveal. Building
# it here, from the same files in the same order the enqueues use, is what stops that.
CHROME_SOURCES = [
    "assets/css/theme-system.css",
    "assets/dsb8-beta2-header.css",
    "assets/css/drawer.css",
    "assets/css/bottom-nav.css",
]
CHROME_BUNDLE = "assets/css/storefront-chrome.min.css"

# The homepage component bundle is the same shape of artifact, and carries the same
# risk of silently drifting from its parts. The order below is the order the shipped
# bundle was built in, recovered from where each file's first selector appears in it.
COMPONENT_SOURCES = [
    "assets/components/" + name
    for name in (
        "base.css", "testimonials.css", "trust-strip.css", "products.css", "newsletter.css",
        "how-it-works.css", "hero.css", "bon-kliyan.css", "text.css", "banner.css",
        "category-chips.css", "faq.css", "why-delicat.css", "favorites.css", "spacer.css",
    )
]
COMPONENT_BUNDLE = "assets/components/all-components.min.css"


def build_bundle(target, sources):
    missing = [s for s in sources if not os.path.exists(os.path.join(ROOT, s))]
    if missing:
        raise SystemExit("bundle sources missing for %s: %s" % (target, ", ".join(missing)))
    head = [
        "/* Generated by scripts/refresh-delicat-assets.py. Do not edit by hand.",
        " * Concatenation, in cascade order, of:",
    ]
    for rel_src in sources:
        head.append(" *   " + rel_src)
    head.append(" */")
    for rel_src in sources:
        with open(os.path.join(ROOT, rel_src), encoding="utf-8") as fh:
            head.append("\n/* --- " + rel_src + " --- */\n" + fh.read().strip())
    text = "\n".join(head) + "\n"
    path = os.path.join(ROOT, target)
    changed = True
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            changed = fh.read() != text
    if changed:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    print("%s %s (%d bytes from %d sources)" % (
        "built   " if changed else "verified", target, len(text.encode("utf-8")), len(sources)))


build_bundle(CHROME_BUNDLE, CHROME_SOURCES)
build_bundle(COMPONENT_BUNDLE, COMPONENT_SOURCES)

# 1. hashed copies -------------------------------------------------------------
sources, hashed = [], []
for dp, _, fns in os.walk(ROOT):
    for fn in fns:
        p = os.path.join(dp, fn)
        r = rel(p)
        if not asset_dir(r) or not r.endswith((".css", ".js")):
            continue
        (hashed if HASHED.match(fn) else sources).append(r)

wanted = {}
for r in sorted(sources):
    digest = sha256(os.path.join(ROOT, r))[:12]
    base, ext = r.rsplit(".", 1)
    target = "%s.%s.%s" % (base, digest, ext)
    wanted[r] = target
    tpath = os.path.join(ROOT, target)
    if not os.path.exists(tpath):
        with open(os.path.join(ROOT, r), "rb") as src, open(tpath, "wb") as dst:
            dst.write(src.read())
        print("created  %s" % target)

# ---- the previous generation stays ------------------------------------------
# Content addressing only works if the files are ADDITIVE. HTML is cached in
# places this build cannot reach - LiteSpeed, Cloudflare, and every phone that
# has already loaded the shop - and all of it asks for the exact filenames that
# were current when it was cached. Deleting the old hashed copy turns those into
# 404s, and a 404 on storefront-chrome.min.<hash>.css is the whole shop rendered
# with no styling at all. That is what "the site broke after updating" was: one
# release dropped the copy the previous release's cached pages still asked for.
#
# So a superseded copy is kept by default and only removed with --prune, which
# is a deliberate act for a release allowed to break in-flight HTML. Keeping
# them costs a few KB per changed file. Removing them costs the storefront.
PRUNE = "--prune" in sys.argv[1:]
keep, dropped = 0, 0
for r in hashed:
    if r in wanted.values():
        continue
    if PRUNE:
        os.remove(os.path.join(ROOT, r))
        dropped += 1
        print("removed  %s (stale, --prune)" % r)
    else:
        keep += 1
if keep:
    print("kept     %d superseded copy(ies) so already-cached pages still resolve" % keep)
if dropped:
    print("PRUNED   %d copy(ies): any HTML cached before this build will 404 on them" % dropped)

# 2. asset-versions.php --------------------------------------------------------
lines = ["<?php", "// Generated content-addressed assets. Original paths retained for compatibility.", "return array("]
for r in sorted(wanted):
    lines.append(" '%s' => '%s'," % (r, wanted[r]))
lines.append(");")
with open(os.path.join(ROOT, "asset-versions.php"), "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print("wrote    asset-versions.php (%d entries)" % len(wanted))

# 3. integrity-manifest.json ---------------------------------------------------
main = open(os.path.join(ROOT, "delicat-builder-v9.php"), encoding="utf-8").read()
m = re.search(r"^\s*\*\s*Version:\s*(\S+)", main, re.M)
version = m.group(1) if m else "unknown"
files, total = {}, 0
for dp, _, fns in os.walk(ROOT):
    for fn in fns:
        p = os.path.join(dp, fn)
        r = rel(p)
        if r == "integrity-manifest.json":
            continue
        size = os.path.getsize(p)
        total += size
        files[r] = {"bytes": size, "sha256": sha256(p)}
manifest = {
    "algorithm": "sha256",
    "built": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    "version": version,
    "bytes": total,
    "count": len(files),
    "files": {k: files[k] for k in sorted(files)},
}

# Keep the previous build stamp when nothing else changed. Without this every
# packaging run rewrites the manifest with a new timestamp and dirties the working
# tree, which makes "is the package in sync with the source?" unanswerable from git.
manifest_path = os.path.join(ROOT, "integrity-manifest.json")
unchanged = False
if os.path.exists(manifest_path):
    try:
        with open(manifest_path, encoding="utf-8") as fh:
            previous = json.load(fh)
        if {k: v for k, v in previous.items() if k != "built"} == {
            k: v for k, v in manifest.items() if k != "built"
        }:
            manifest["built"] = previous.get("built", manifest["built"])
            unchanged = True
    except (OSError, ValueError):
        pass

with open(manifest_path, "w", encoding="utf-8") as fh:
    json.dump(manifest, fh, indent=2)
    fh.write("\n")
print(
    "%s integrity-manifest.json (%d files, version %s)"
    % ("verified" if unchanged else "wrote   ", len(files), version)
)
